theme: jekyll-theme-minimal
title: Muskaan Verma
description: Pushing frontiers in Brain-Computer Interfacing assisted agricultural technologies, amalgamation of cognitive linguistics and natural language processing AI
