theme: jekyll-theme-minimal
title: Muskaan Verma
description: Pushing frontiers in Brain-computer interface (BCI) assisted agricultural technologies and amalgamation of cognitive linguistics and natural language processing AI
